export enum ErrorCodes {
  CREDENTIALS_INVALID = "CREDENTIALS_INVALID",
  CODE_INVALID = "CODE_INVALID",
  CODE_ALREADY_USED = "CODE_ALREADY_USED",
  DEVICE_ALREADY_TRIALED = "DEVICE_ALREADY_TRIALED",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
}

export enum HttpStatusCodes {
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL_SERVER = 500,
}